#indica la version de Docker Compose utilizada
version: '3.9'
#Bloque de servicios, indica los contenedores a utilizar.
services:
  weba:       #nombre del servicio
    build: .
    env_file: #Indica el parametro para
      - .env
    environment:    #variable de ambiente
      - NOMBRE_APP=$AMBIENTE
      - server.port=8080
    expose:
      - 8080
    restart: always
    networks:    #red para conectar los equipos.
      - red-app
      
  webb: #nombre del servicio
    build: .
    env_file: #Indica el parametro para
      - .env
    environment: #variable de ambiente
      - NOMBRE_APP=$AMBIENTE
      - server.port=8081
    expose:
      - 8081
    restart: always
    networks: #red para conectar los equipos.
      - red-app

  webc: #nombre del servicio
    build: .
    env_file: #Indica el parametro para
      - .env
    environment: #variable de ambiente
      - NOMBRE_APP=$AMBIENTE
      - server.port=8082
    expose:
      - 8082
    restart: always
    networks: #red para conectar los equipos.
      - red-app
      
  haproxy:
    environment:
      - CERT1=elb.playdomtv.me
      - EMAIL=radf0001@ce.pucmm.edu.do
      - STAGING=false
    volumes:
      - ./haproxy/haproxy.cfg:/etc/haproxy/haproxy.cfg
    links:
      - weba
      - webb
      - webc
    networks:
      - red-app
    ports:
      - '80:80'
      - '443:443'
    image: 'ghcr.io/tomdess/docker-haproxy-certbot:master'

networks:  #bloque para las redes
  red-app:   #indicando la red definida
